### ISSUE TITLE
Is this package used actively?

### ISSUE THREAD

**Issue by emiliom** [NWQMC/pywqp#6]
I see that the last activity here on this repo was about 3.5 years ago. 

I'm aware of ongoing USGS-CIDA work on the `dataRetrieval` R package for WQP data access. In contrast, `pywqp` seems very stale, and even at https://www.waterqualitydata.us/webservices_documentation/ it says "This client has limited support that this time".  On the other hand, if the WQP access API and WQX formats haven't changed much in the last couple of years, that may not be a problem ...

@jkreft-usgs, should I bother with this package? As you might guess, I do want something in Python. If it's still useful, are there any meaty examples out there? What's on `README.md` is fairly fragmented.

On a related note, do you have any familiarity with the [pyoos](https://github.com/ioos/pyoos) wqp "collector" & wqx parser? I do use pyoos (and have contributed to it) but have never tried the wqp/wqx stuff. Would be interested in the perspective of someone from outside the pyoos dev team.

Pinging @aufdenkampe, b/c my inquiry is under the umbrella of the [WikiWatershed portal](https://app.wikiwatershed.org) work that he leads, which just folded in the cross-catalog search from the [BiG-CZ Portal](https://portal.bigcz.org/) that @jkreft-usgs saw at our workshop last November. We'd like to integrate the Water Quality Portal catalog.

Thanks!

**Comment by jkreft-usgs** [comment]
Hey cool!  The reality is that this package may have some limited utility but yeah, it hasn't been properly maintained for years.  Other priorities, such as getting new endpoints out, have taken priority.  The good thing is that there isn't THAT much need to really use the package- requests and pandas gets you most of the way there.  I would be happy to work with you to get WQP data into wikiwatersheds. Also, I have not seen the pyOOS collector, except in action on our services- Hawaii hits our services a few hundred times a day looking for new data.

**Comment by emiliom** [comment]
Thanks for the comments, @jkreft-usgs. 

I'll start going over the web service docs to get a better feel for this.

Fun to hear that someone is using pyoos to hit your service operationally. I'm guessing that's PacIOOS. I probably won't try to use pyoos in the wikiwatershed portal (it comes with overhead that may be too much in that context), but there may be wqp code in there that I can reuse.

I'll close this issue, since the answer seems to be that `pywqp` is not the answer.

**Comment by jkreft-usgs** [comment]
yes, I would say to actually stay away from parsing the wqx xml if you can help it.  It is deeply nested and kind of gnarly.  If you start a separate project, I would be happy to contribute

**Comment by aufdenkampe** [comment]
@emiliom thanks for initiating this discussion!
@jkreft-usgs, thanks for offering to help us. We want something that very performant, so I like the idea of avoiding XML. Do you just use JSON responses or is there a more direct integration with Pandas data frames?

**Comment by jkreft-usgs** [comment]
The fastest way to get data into a Pandas dataframe would be to stream the tsv into pandas, which is the approach we take to populate a redis cache quickly with a reasonable memory footprint.
There is a tsv generator [here](https://github.com/NWQMC/WQP_UI/blob/master/wqp/utils.py#L304) that we call on a requests object with streaming=True [here](https://github.com/NWQMC/WQP_UI/blob/master/wqp/tasks.py#L44).
